name: pgxRpi
owner: iuc
description: pgxLoader and pgxFreqplot functions from pgxRpi 1.2.0
homepage_url: https://github.com/progenetix/pgxRpi
long_description: |
    pgxRpi is an R wrapper package for the Progenetix REST API that leverages the capabilities of the Beacon v2 specification. It also provides functions to enhance the visualisation of the retrieved data.
remote_repository_url:  https://github.com/galaxyproject/tools-iuc/tree/master/tools/pgxRpi
type: unrestricted
categories:
- Variant Analysis